/*
* generated by Xtext
*/
package de.tfritsch.psdt;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PostscriptStandaloneSetup extends PostscriptStandaloneSetupGenerated{

	public static void doSetup() {
		new PostscriptStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

