/*
 * generated by Xtext
 */
package de.tfritsch.psdt;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PostscriptRuntimeModule extends de.tfritsch.psdt.AbstractPostscriptRuntimeModule {

}
