language: java

env: DISPLAY=:99.0

cache:
  directories:
  - $HOME/.m2

install: gs -v

before_script:
  - sh -e /etc/init.d/xvfb start
  - echo "MAVEN_OPTS='-Xmx768m -XX:MaxPermSize=384m'" > ~/.mavenrc

script:
  - mvn verify
