/*
 * generated by Xtext
 */
package de.tfritsch.psdt.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PostscriptUiModule extends de.tfritsch.psdt.ui.AbstractPostscriptUiModule {
	public PostscriptUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
