/*
 * generated by Xtext
 */
package de.tfritsch.psdt.ui.contentassist

import de.tfritsch.psdt.ui.contentassist.AbstractPostscriptProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class PostscriptProposalProvider extends AbstractPostscriptProposalProvider {
}
